---
title: "Analysis"
output: html_notebook
--
# Creating the dataframes wanted for our different kinds of analyses

```{r}
# setting the working directory to my local computer
setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')

games_src <- read.csv('./data/final_games.csv', row.names = 1, header= TRUE)
tech_src <- read.csv('./data/final_tech.csv', row.names = 1, header= TRUE)
design_src <- read.csv('./data/final_design.csv', row.names = 1, header= TRUE)

games_meta <- games_src[, c(1:10)]
games_vec <- cbind(games_src[, c(11:50)], pledged_binary = games_src$pledged_binary, peldged_percentage =games_src$pledged_percentage)

tech_meta <- tech_src[, c(1:10)]
tech_vec <- cbind(tech_src[, c(11:50)],pledged_binary = tech_src$pledged_binary, peldged_percentage =tech_src$pledged_percentage)

design_meta <- design_src[, c(1:10)]
design_vec <- cbind(design_src[, c(11:50)], pledged_binary = design_src$pledged_binary, peldged_percentage = design_src$pledged_percentage)

```


```{r}
summary(design_meta)

```

