---
title: "Horizontal analysis of TECH"
output: html_notebook
---
# Loading data and adjusting variables


```{r}
# change wd for your own computer, this path is mine
setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')
library(stargazer)
data_src <- read.csv('./data/final_tech.csv', row.names = 1, header= TRUE)

df <- data_src

# changing the location to binary
df$location_binary <- ifelse(df$location == 'us', 1, 0)

df$subcategory_binary <- ifelse(df$Category %in% c('Hardware', 'Gadgets', 'Wearables'), 1, 0)

df$location_binary <- as.logical(df$location_binary)
df$subcategory <- as.factor(df$subcategory)
df$launch_date <- as.Date(df$launch_date)
df$degree_of_diff <- as.numeric(gsub("\\[|\\]", "", df$degree_of_diff))


df$pledged_binary <- NULL
df$top_country <- NULL
df$location <- NULL
df$project_slug <- NULL
df$Category <- NULL
df$Staff_recommended <- NULL
df$subcategory_binary <- NULL
df$subcategory <- NULL

stargazer(df[1:7])

```


```{r}
hist(df$pledged_percentage, breaks = 10, main ='histogram of percentage pledged')
df$pledged_percentage <- log(df$pledged_percentage) 
outliers <- boxplot(df$pledged_percentage, plot=FALSE)$out
df<- df[-which(df$pledged_percentage %in% outliers),]
hist(df$pledged_percentage, breaks = 10, main ='histogram of percentage pledged after log transform')

hist(df$Pledge_USD, breaks = 10, main ='histogram of pledge amount')
df$Pledge_USD <- log(df$Pledge_USD) 
outliers <- boxplot(df$Pledge_USD, plot=FALSE)$out
df<- df[-which(df$Pledge_USD %in% outliers),]
hist(df$Pledge_USD, breaks = 10, main ='histogram of pledge amount after log transform')

df$Number_Backers <- log(df$Number_Backers)
df$Goal_USD <- log(df$Goal_USD)

```



#Creating target variable
```{r}
scale_O1 <- function(x){(x-min(x))/(max(x)-min(x))}


df$pledged_percentage <- scale_O1(df$pledged_percentage)
df$Number_Backers <- scale_O1(df$Number_Backers)
df$degree_of_diff <- scale_O1(df$degree_of_diff)
df$Creator_nb_projects <- scale_O1(df$Creator_nb_projects)
df$Goal_USD <- scale_O1(df$Goal_USD)
df$Pledge_USD <- scale_O1(df$Pledge_USD)

```

# Correlation table
```{r}
bootcamp2021::corrMat(df[c('pledged_percentage', 'Number_Backers', 'degree_of_diff', 'Creator_nb_projects', 'Goal_USD', 'Pledge_USD')])
```

```{r}
lm1 <- lm(pledged_percentage ~ location_binary  + Number_Backers + Creator_nb_projects, data = df)
lm2 <- lm(pledged_percentage ~ location_binary + degree_of_diff + Number_Backers + Creator_nb_projects, data = df)
lm4 <- lm(Pledge_USD ~ location_binary  + Number_Backers + Creator_nb_projects + Goal_USD, data = df)
lm3 <- lm(Pledge_USD ~ location_binary + degree_of_diff + Number_Backers + Creator_nb_projects + Goal_USD, data = df)

stargazer(lm1, lm2, lm4, lm3, title="Regression Results",
align=TRUE, dep.var.labels=c("Percentage Pledged","Pledge Amount"),
covariate.labels=c("Location","Degree of Differentiation",
"Number of Backers","Creator projects","Goal Amount"),
omit.stat=c("LL","ser","f"), no.space=TRUE)

summary(lm2)
summary(lm3)
```




# inverted U
```{r}
xmin = 0; xmax = 1
df1 = subset(df, select = c(pledged_percentage,degree_of_diff,Number_Backers,Creator_nb_projects ))
plot( df1$degree_of_diff, df1$pledged_percentage, xlim=c(xmin,xmax) )


model_inv_u1 <- lm(pledged_percentage ~  poly(degree_of_diff,2) + Number_Backers + Creator_nb_projects, data = df1)
model_inv_u2 <- lm(pledged_percentage ~   Number_Backers + Creator_nb_projects, data = df1)

N = 1e4
means = colMeans(df1)
dummyDF = t(as.data.frame(means))
for(i in 2:N){dummyDF=rbind(dummyDF,means)} 
xv=seq(xmin,xmax, length.out=N)
dummyDF[,2] = xv
dummyDF = as.data.frame(dummyDF)
yv=predict(model_inv_u1, newdata=subset(dummyDF, select=c(-pledged_percentage)))
lines(xv, yv, col='red', lwd=2)


```
# Robustness check
```{r}
xmin = 0; xmax = 1
df2 = subset(df, select = c(Pledge_USD,degree_of_diff,Number_Backers,Creator_nb_projects, Goal_USD ))
plot( df2$degree_of_diff, df2$Pledge_USD, xlim=c(xmin,xmax) )


model_inv_u3 <- lm(Pledge_USD ~  poly(degree_of_diff,2) + Number_Backers + Creator_nb_projects + Goal_USD, data = df2)
model_inv_u4 <- lm(Pledge_USD ~   Number_Backers + Creator_nb_projects + Goal_USD, data = df2)

summary(model_inv_u3)


N = 1e4
means = colMeans(df2)
dummyDF = t(as.data.frame(means))
for(i in 2:N){dummyDF=rbind(dummyDF,means)} 
xv=seq(xmin,xmax, length.out=N)
dummyDF[,2] = xv
dummyDF = as.data.frame(dummyDF)
yv=predict(model_inv_u3, newdata=subset(dummyDF, select=c(-Pledge_USD)))
lines(xv, yv, col='red', lwd=2)

```
```{r}
covariate.labels=c("Degree of Differentiation","(Degree of Differentiation)^2", "Number of Backers","Creator projects","Goal Amount")

stargazer(model_inv_u2, model_inv_u1, model_inv_u4, model_inv_u3,  title="Polynomial Regression Results",
align=TRUE, dep.var.labels=c("Percentage Pledged","Pledge Amount"),covariate.labels=c("Degree of Differentiation","(Degree of Differentiation)^2", "Number of Backers","Creator projects","Goal Amount"),
omit.stat=c("LL","ser","f"), no.space=TRUE)
```
