---
title: "Horizontal analysis of GAMES"
output: html_notebook
---
# Loading data and adjusting variables


```{r}
# change wd for your own computer, this path is mine
# 
library(broom)
setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')

data_src <- read.csv('./data/final_games.csv', row.names = 1, header= TRUE)

df <- data_src

# changing the location to binary
df$location_binary <- ifelse(df$location == 'us', 1, 0)

df$subcategory[df$Category == 'Tabletop Games'] <- 1
df$subcategory[df$Category == 'Video Games'] <- 2
df$subcategory[!(df$Category %in% c('Tabletop Games', 'Video Games'))] <- 3

df$location_binary <- as.logical(df$location_binary)
df$subcategory <- as.factor(df$subcategory)
df$launch_date <- as.Date(df$launch_date)
df$degree_of_diff <- as.numeric(gsub("\\[|\\]", "", df$degree_of_diff))



df$pledged_binary <- NULL
df$top_country <- NULL
df$location <- NULL
df$project_slug <- NULL
df$Category <- NULL
df$Staff_recommended <- NULL
df$subcategory <- NULL

#df$meta = 'games'
# write.csv(df, './data/adjusted_games.csv')

```

# Filtering out outliers 
```{r}
boxplot(df$Number_Backers)
df <- df[df$Number_Backers < quantile(df$Number_Backers, 0.8, na.rm = FALSE),]
boxplot(df$Number_Backers)
summary(df$Number_Backers)


boxplot(df$pledged_percentage)
df <- df[df$pledged_percentage < quantile(df$pledged_percentage, 0.8, na.rm = FALSE),]
boxplot(df$pledged_percentage)
summary(df$pledged_percentage)

boxplot(df$Goal_USD)
df <- df[df$Goal_USD < quantile(df$Goal_USD, 0.8, na.rm = FALSE),]
boxplot(df$Goal_USD)
summary(df$Goal_USD)

boxplot(df$Pledge_USD)
df <- df[df$Pledge_USD < quantile(df$Goal_USD, 0.95, na.rm = FALSE),]
boxplot(df$Pledge_USD)
summary(df$Pledge_USD)
```

#Creating target variable
```{r}
scale_O1 <- function(x){(x-min(x))/(max(x)-min(x))}


df$pledged_percentage <- scale_O1(df$pledged_percentage)
df$Number_Backers <- scale_O1(df$Number_Backers)
df$degree_of_diff <- scale_O1(df$degree_of_diff)
df$Creator_nb_projects <- scale_O1(df$Creator_nb_projects)
df$Goal_USD <- scale_O1(df$Goal_USD)
df$Pledge_USD <- scale_O1(df$Pledge_USD)

```

# Correlation table
```{r}
bootcamp2021::corrMat(df[c('pledged_percentage', 'Number_Backers', 'degree_of_diff', 'Creator_nb_projects', 'Goal_USD', 'Pledge_USD')])
```



# OLS
```{r}
model1 <- lm(pledged_percentage ~ location_binary + degree_of_diff + Number_Backers + Creator_nb_projects, data = df)

summary(model1)
plot(model1)

setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')
write.csv(tidy(model1), './docs/games_percentage_model_coefs.csv')
```
```{r}

model2 <- lm(pledged_percentage ~ . - degree_of_diff - Pledge_USD - Goal_USD, data = df)

summary(model2)
plot(model2)
setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')
write.csv(tidy(model2), './docs/games_topics_model_coefs.csv')
```


# With Pledge and Goal as target and control

```{r}

model3 <- lm(Pledge_USD ~ location_binary + degree_of_diff + Number_Backers + Creator_nb_projects + Goal_USD, data = df)

summary(model3)
plot(model3)

setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')
write.csv(tidy(model3), './docs/games_pledge_model_coefs.csv')

```

# inverted U
```{r}
xmin = 0; xmax = 1
df = subset(df, select = c(pledged_percentage,degree_of_diff,Number_Backers,Creator_nb_projects ))
plot( df$degree_of_diff, df$pledged_percentage, xlim=c(xmin,xmax) )


model_inv_u <- lm(pledged_percentage ~  poly(degree_of_diff,2) + Number_Backers + Creator_nb_projects, data = df)

N = 1e4
means = colMeans(df)
dummyDF = t(as.data.frame(means))
for(i in 2:N){dummyDF=rbind(dummyDF,means)} 
xv=seq(xmin,xmax, length.out=N)
dummyDF[,2] = xv
dummyDF = as.data.frame(dummyDF)
yv=predict(model_inv_u, newdata=subset(dummyDF, select=c(-pledged_percentage)))
lines(xv, yv, col='red', lwd=2)

```


