---
title: "Post-presentations notebook"
output: html_notebook
---

# Unifying data

```{r}
setwd('C:/Gergo-mappa/projects/programming/projects/jads/sbm/jads_2021_g9_sbm')

games <- read.csv('./data/adjusted_games.csv', row.names = 1)
tech <- read.csv('./data/adjusted_tech.csv', row.names = 1)
design <- read.csv('./data/adjusted_design.csv', row.names = 1)

df <- Reduce(rbind, list(games, tech, design))
df$meta = as.factor(df$meta)
df$launch_date = as.Date(df$launch_date)
```
# Outlier filtering
```{r}
boxplot(df$Number_Backers)
df <- df[df$Number_Backers < quantile(df$Number_Backers, 0.8, na.rm = FALSE),]
boxplot(df$Number_Backers)
summary(df$Number_Backers)


boxplot(df$pledged_percentage)
df <- df[df$pledged_percentage < quantile(df$pledged_percentage, 0.8, na.rm = FALSE),]
boxplot(df$pledged_percentage)
summary(df$pledged_percentage)

boxplot(df$Goal_USD)
df <- df[df$Goal_USD < quantile(df$Goal_USD, 0.8, na.rm = FALSE),]
boxplot(df$Goal_USD)
summary(df$Goal_USD)

boxplot(df$Pledge_USD)
df <- df[df$Pledge_USD < quantile(df$Goal_USD, 0.95, na.rm = FALSE),]
boxplot(df$Pledge_USD)
summary(df$Pledge_USD)

```
#Scaling
```{r}
scale_O1 <- function(x){(x-min(x))/(max(x)-min(x))}


df$pledged_percentage <- scale_O1(df$pledged_percentage)
df$Number_Backers <- scale_O1(df$Number_Backers)
df$degree_of_diff <- scale_O1(df$degree_of_diff)
df$Creator_nb_projects <- scale_O1(df$Creator_nb_projects)
df$Goal_USD <- scale_O1(df$Goal_USD)
df$Pledge_USD <- scale_O1(df$Pledge_USD)
```
# Correlation table
```{r}
#later cuz im tired
bootcamp2021::corrMat(df[c('pledged_percentage', 'Number_Backers', 'degree_of_diff', 'Creator_nb_projects', 'Goal_USD', 'Pledge_USD')])
```
# First model
```{r}

percentage_model <- lm(pledged_percentage ~ Number_Backers + Creator_nb_projects + degree_of_diff*meta + launch_date + location_binary, data = df)

summary(percentage_model)
plot(percentage_model)


```


